# Custom Language File for Launcher Customizer

[ejs.app]
title = "둥지 서버"

[ejs.landing]
mediaGitHubURL = "https://github.com/CustomLauncherLab/nest-huinomok"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"
mediaSoopURL = "https://ch.sooplive.co.kr/huinomok"
mediaChzzkURL = "#"
screenshotsTooltip = "스크린샷"

[ejs.settings]
sourceGithubLink = "https://github.com/CustomLauncherLab/nest-huinomok"
supportLink = "https://github.com/CustomLauncherLab/nest-huinomok/issues"

[ejs.welcome]
welcomeHeader = "둥지 서버"
welcomeDescription = ""
welcomeDescCTA = "계속하기 버튼을 눌러 계속 진행하여 주세요."